services:
  redis:
    image: redis:8-alpine
    container_name: beehive-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ../../data/redis:/data
    networks:
      - beehive-net

networks:
  beehive-net:
    driver: bridge
