// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // text / image / system / ...
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"` // when type = text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageBody) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MessageBody) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PostMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId    string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FromUserId     string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId       string                 `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"` // for single chat, optional for group
	Body           *MessageBody           `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *PostMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *PostMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PostMessageRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *PostMessageRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *PostMessageRequest) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type PostMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId    string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ServerTime     int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *PostMessageResponse) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *PostMessageResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PostMessageResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type GetHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BeforeTime     int64                  `protobuf:"varint,2,opt,name=before_time,json=beforeTime,proto3" json:"before_time,omitempty"` // optional: messages before this time
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetHistoryRequest) GetBeforeTime() int64 {
	if x != nil {
		return x.BeforeTime
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MessageRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId    string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	FromUserId     string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId       string                 `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Body           *MessageBody           `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ServerTime     int64                  `protobuf:"varint,6,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageRecord) Reset() {
	*x = MessageRecord{}
	mi := &file_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecord) ProtoMessage() {}

func (x *MessageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecord.ProtoReflect.Descriptor instead.
func (*MessageRecord) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRecord) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *MessageRecord) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageRecord) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *MessageRecord) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *MessageRecord) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MessageRecord) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MessageRecord       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryResponse) GetItems() []*MessageRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetLastMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationIds []string               `protobuf:"bytes,1,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLastMessagesRequest) Reset() {
	*x = GetLastMessagesRequest{}
	mi := &file_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessagesRequest) ProtoMessage() {}

func (x *GetLastMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetLastMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastMessagesRequest) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type GetLastMessagesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	LastMessages  map[string]*MessageRecord `protobuf:"bytes,1,rep,name=last_messages,json=lastMessages,proto3" json:"last_messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessagesResponse) Reset() {
	*x = GetLastMessagesResponse{}
	mi := &file_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessagesResponse) ProtoMessage() {}

func (x *GetLastMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetLastMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetLastMessagesResponse) GetLastMessages() map[string]*MessageRecord {
	if x != nil {
		return x.LastMessages
	}
	return nil
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ServerMsgId    string                 `protobuf:"bytes,3,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MarkReadRequest) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{9}
}

type GetUnreadCountsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationIds []string               `protobuf:"bytes,2,rep,name=conversation_ids,json=conversationIds,proto3" json:"conversation_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUnreadCountsRequest) Reset() {
	*x = GetUnreadCountsRequest{}
	mi := &file_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsRequest) ProtoMessage() {}

func (x *GetUnreadCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetUnreadCountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUnreadCountsRequest) GetConversationIds() []string {
	if x != nil {
		return x.ConversationIds
	}
	return nil
}

type GetUnreadCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int32       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountsResponse) Reset() {
	*x = GetUnreadCountsResponse{}
	mi := &file_proto_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountsResponse) ProtoMessage() {}

func (x *GetUnreadCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountsResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetUnreadCountsResponse) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\x0fbeehive.message\"5\n" +
	"\vMessageBody\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xd3\x01\n" +
	"\x12PostMessageRequest\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tR\btoUserId\x120\n" +
	"\x04body\x18\x05 \x01(\v2\x1c.beehive.message.MessageBodyR\x04body\"\x83\x01\n" +
	"\x13PostMessageResponse\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"s\n" +
	"\x11GetHistoryRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1f\n" +
	"\vbefore_time\x18\x02 \x01(\x03R\n" +
	"beforeTime\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xef\x01\n" +
	"\rMessageRecord\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tR\btoUserId\x120\n" +
	"\x04body\x18\x05 \x01(\v2\x1c.beehive.message.MessageBodyR\x04body\x12\x1f\n" +
	"\vserver_time\x18\x06 \x01(\x03R\n" +
	"serverTime\"e\n" +
	"\x12GetHistoryResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.beehive.message.MessageRecordR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"C\n" +
	"\x16GetLastMessagesRequest\x12)\n" +
	"\x10conversation_ids\x18\x01 \x03(\tR\x0fconversationIds\"\xdb\x01\n" +
	"\x17GetLastMessagesResponse\x12_\n" +
	"\rlast_messages\x18\x01 \x03(\v2:.beehive.message.GetLastMessagesResponse.LastMessagesEntryR\flastMessages\x1a_\n" +
	"\x11LastMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.beehive.message.MessageRecordR\x05value:\x028\x01\"w\n" +
	"\x0fMarkReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\"\n" +
	"\rserver_msg_id\x18\x03 \x01(\tR\vserverMsgId\"\x12\n" +
	"\x10MarkReadResponse\"\\\n" +
	"\x16GetUnreadCountsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10conversation_ids\x18\x02 \x03(\tR\x0fconversationIds\"\xa2\x01\n" +
	"\x17GetUnreadCountsResponse\x12L\n" +
	"\x06counts\x18\x01 \x03(\v24.beehive.message.GetUnreadCountsResponse.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\xde\x03\n" +
	"\x0eMessageService\x12X\n" +
	"\vPostMessage\x12#.beehive.message.PostMessageRequest\x1a$.beehive.message.PostMessageResponse\x12U\n" +
	"\n" +
	"GetHistory\x12\".beehive.message.GetHistoryRequest\x1a#.beehive.message.GetHistoryResponse\x12d\n" +
	"\x0fGetLastMessages\x12'.beehive.message.GetLastMessagesRequest\x1a(.beehive.message.GetLastMessagesResponse\x12O\n" +
	"\bMarkRead\x12 .beehive.message.MarkReadRequest\x1a!.beehive.message.MarkReadResponse\x12d\n" +
	"\x0fGetUnreadCounts\x12'.beehive.message.GetUnreadCountsRequest\x1a(.beehive.message.GetUnreadCountsResponseB7Z5github.com/HappyLadySauce/Beehive/services/message/pbb\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_message_proto_goTypes = []any{
	(*MessageBody)(nil),             // 0: beehive.message.MessageBody
	(*PostMessageRequest)(nil),      // 1: beehive.message.PostMessageRequest
	(*PostMessageResponse)(nil),     // 2: beehive.message.PostMessageResponse
	(*GetHistoryRequest)(nil),       // 3: beehive.message.GetHistoryRequest
	(*MessageRecord)(nil),           // 4: beehive.message.MessageRecord
	(*GetHistoryResponse)(nil),      // 5: beehive.message.GetHistoryResponse
	(*GetLastMessagesRequest)(nil),  // 6: beehive.message.GetLastMessagesRequest
	(*GetLastMessagesResponse)(nil), // 7: beehive.message.GetLastMessagesResponse
	(*MarkReadRequest)(nil),         // 8: beehive.message.MarkReadRequest
	(*MarkReadResponse)(nil),        // 9: beehive.message.MarkReadResponse
	(*GetUnreadCountsRequest)(nil),  // 10: beehive.message.GetUnreadCountsRequest
	(*GetUnreadCountsResponse)(nil), // 11: beehive.message.GetUnreadCountsResponse
	nil,                             // 12: beehive.message.GetLastMessagesResponse.LastMessagesEntry
	nil,                             // 13: beehive.message.GetUnreadCountsResponse.CountsEntry
}
var file_proto_message_proto_depIdxs = []int32{
	0,  // 0: beehive.message.PostMessageRequest.body:type_name -> beehive.message.MessageBody
	0,  // 1: beehive.message.MessageRecord.body:type_name -> beehive.message.MessageBody
	4,  // 2: beehive.message.GetHistoryResponse.items:type_name -> beehive.message.MessageRecord
	12, // 3: beehive.message.GetLastMessagesResponse.last_messages:type_name -> beehive.message.GetLastMessagesResponse.LastMessagesEntry
	13, // 4: beehive.message.GetUnreadCountsResponse.counts:type_name -> beehive.message.GetUnreadCountsResponse.CountsEntry
	4,  // 5: beehive.message.GetLastMessagesResponse.LastMessagesEntry.value:type_name -> beehive.message.MessageRecord
	1,  // 6: beehive.message.MessageService.PostMessage:input_type -> beehive.message.PostMessageRequest
	3,  // 7: beehive.message.MessageService.GetHistory:input_type -> beehive.message.GetHistoryRequest
	6,  // 8: beehive.message.MessageService.GetLastMessages:input_type -> beehive.message.GetLastMessagesRequest
	8,  // 9: beehive.message.MessageService.MarkRead:input_type -> beehive.message.MarkReadRequest
	10, // 10: beehive.message.MessageService.GetUnreadCounts:input_type -> beehive.message.GetUnreadCountsRequest
	2,  // 11: beehive.message.MessageService.PostMessage:output_type -> beehive.message.PostMessageResponse
	5,  // 12: beehive.message.MessageService.GetHistory:output_type -> beehive.message.GetHistoryResponse
	7,  // 13: beehive.message.MessageService.GetLastMessages:output_type -> beehive.message.GetLastMessagesResponse
	9,  // 14: beehive.message.MessageService.MarkRead:output_type -> beehive.message.MarkReadResponse
	11, // 15: beehive.message.MessageService.GetUnreadCounts:output_type -> beehive.message.GetUnreadCountsResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
