// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: file.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-file/file"
	"github.com/HappyLadySauce/Beehive/app/beehive-file/internal/logic"
	"github.com/HappyLadySauce/Beehive/app/beehive-file/internal/svc"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传文件
func (s *FileServiceServer) UploadFile(ctx context.Context, in *file.UploadFileRequest) (*file.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

// 获取文件信息
func (s *FileServiceServer) GetFileInfo(ctx context.Context, in *file.GetFileInfoRequest) (*file.FileInfoResponse, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}

// 删除文件
func (s *FileServiceServer) DeleteFile(ctx context.Context, in *file.DeleteFileRequest) (*file.CommonResponse, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}

// 检查文件是否存在（去重）
func (s *FileServiceServer) CheckFileExists(ctx context.Context, in *file.CheckFileExistsRequest) (*file.CheckFileExistsResponse, error) {
	l := logic.NewCheckFileExistsLogic(ctx, s.svcCtx)
	return l.CheckFileExists(in)
}

// 初始化分片上传
func (s *FileServiceServer) InitMultipartUpload(ctx context.Context, in *file.InitMultipartUploadRequest) (*file.InitMultipartUploadResponse, error) {
	l := logic.NewInitMultipartUploadLogic(ctx, s.svcCtx)
	return l.InitMultipartUpload(in)
}

// 上传文件分片
func (s *FileServiceServer) UploadPart(ctx context.Context, in *file.UploadPartRequest) (*file.UploadPartResponse, error) {
	l := logic.NewUploadPartLogic(ctx, s.svcCtx)
	return l.UploadPart(in)
}

// 完成分片上传
func (s *FileServiceServer) CompleteMultipartUpload(ctx context.Context, in *file.CompleteMultipartUploadRequest) (*file.UploadFileResponse, error) {
	l := logic.NewCompleteMultipartUploadLogic(ctx, s.svcCtx)
	return l.CompleteMultipartUpload(in)
}
