// pkg/api/proto/presence/v1/presence.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: presence.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserOnlineRequest 用户上线请求
type UserOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
}

func (x *UserOnlineRequest) Reset() {
	*x = UserOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineRequest) ProtoMessage() {}

func (x *UserOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineRequest.ProtoReflect.Descriptor instead.
func (*UserOnlineRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{0}
}

func (x *UserOnlineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UserOnlineResponse 用户上线响应
type UserOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                   // 是否成功
	OnlineAt int64 `protobuf:"varint,2,opt,name=online_at,json=onlineAt,proto3" json:"online_at,omitempty"` // 上线时间（Unix 时间戳）
}

func (x *UserOnlineResponse) Reset() {
	*x = UserOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnlineResponse) ProtoMessage() {}

func (x *UserOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnlineResponse.ProtoReflect.Descriptor instead.
func (*UserOnlineResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{1}
}

func (x *UserOnlineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserOnlineResponse) GetOnlineAt() int64 {
	if x != nil {
		return x.OnlineAt
	}
	return 0
}

// UserOfflineRequest 用户下线请求
type UserOfflineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
}

func (x *UserOfflineRequest) Reset() {
	*x = UserOfflineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfflineRequest) ProtoMessage() {}

func (x *UserOfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfflineRequest.ProtoReflect.Descriptor instead.
func (*UserOfflineRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{2}
}

func (x *UserOfflineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// UserOfflineResponse 用户下线响应
type UserOfflineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // 是否成功
	OfflineAt int64 `protobuf:"varint,2,opt,name=offline_at,json=offlineAt,proto3" json:"offline_at,omitempty"` // 下线时间（Unix 时间戳）
}

func (x *UserOfflineResponse) Reset() {
	*x = UserOfflineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOfflineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOfflineResponse) ProtoMessage() {}

func (x *UserOfflineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOfflineResponse.ProtoReflect.Descriptor instead.
func (*UserOfflineResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{3}
}

func (x *UserOfflineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserOfflineResponse) GetOfflineAt() int64 {
	if x != nil {
		return x.OfflineAt
	}
	return 0
}

// GetOnlineUsersRequest 批量获取用户在线状态请求
type GetOnlineUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 用户ID列表
}

func (x *GetOnlineUsersRequest) Reset() {
	*x = GetOnlineUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnlineUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersRequest) ProtoMessage() {}

func (x *GetOnlineUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnlineUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// GetOnlineUsersResponse 批量获取用户在线状态响应
type GetOnlineUsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*UserPresenceInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 用户在线状态列表
}

func (x *GetOnlineUsersResponse) Reset() {
	*x = GetOnlineUsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineUsersResponse) ProtoMessage() {}

func (x *GetOnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{5}
}

func (x *GetOnlineUsersResponse) GetUsers() []*UserPresenceInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// IsUserOnlineRequest 检查用户是否在线请求
type IsUserOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
}

func (x *IsUserOnlineRequest) Reset() {
	*x = IsUserOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsUserOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserOnlineRequest) ProtoMessage() {}

func (x *IsUserOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserOnlineRequest.ProtoReflect.Descriptor instead.
func (*IsUserOnlineRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{6}
}

func (x *IsUserOnlineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// IsUserOnlineResponse 检查用户是否在线响应
type IsUserOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Online     bool  `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`                             // 是否在线
	LastSeenAt int64 `protobuf:"varint,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"` // 最后在线时间（Unix 时间戳，离线时返回）
}

func (x *IsUserOnlineResponse) Reset() {
	*x = IsUserOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsUserOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserOnlineResponse) ProtoMessage() {}

func (x *IsUserOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserOnlineResponse.ProtoReflect.Descriptor instead.
func (*IsUserOnlineResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{7}
}

func (x *IsUserOnlineResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *IsUserOnlineResponse) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

// GetUserPresenceRequest 获取用户详细在线状态请求
type GetUserPresenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID
}

func (x *GetUserPresenceRequest) Reset() {
	*x = GetUserPresenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPresenceRequest) ProtoMessage() {}

func (x *GetUserPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetUserPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserPresenceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetUserPresenceResponse 获取用户详细在线状态响应
type GetUserPresenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Presence *UserPresenceInfo `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"` // 用户在线状态信息
}

func (x *GetUserPresenceResponse) Reset() {
	*x = GetUserPresenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPresenceResponse) ProtoMessage() {}

func (x *GetUserPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetUserPresenceResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserPresenceResponse) GetPresence() *UserPresenceInfo {
	if x != nil {
		return x.Presence
	}
	return nil
}

// UserPresenceInfo 用户在线状态信息
type UserPresenceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 用户ID
	Online     bool   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`                             // 是否在线
	Status     string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // 状态: online, offline, busy, idle, invisible
	LastSeenAt int64  `protobuf:"varint,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"` // 最后在线时间（Unix 时间戳）
	OnlineAt   int64  `protobuf:"varint,5,opt,name=online_at,json=onlineAt,proto3" json:"online_at,omitempty"`         // 上线时间（Unix 时间戳，仅在线时有效）
}

func (x *UserPresenceInfo) Reset() {
	*x = UserPresenceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_presence_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPresenceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPresenceInfo) ProtoMessage() {}

func (x *UserPresenceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPresenceInfo.ProtoReflect.Descriptor instead.
func (*UserPresenceInfo) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{10}
}

func (x *UserPresenceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPresenceInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *UserPresenceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserPresenceInfo) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *UserPresenceInfo) GetOnlineAt() int64 {
	if x != nil {
		return x.OnlineAt
	}
	return 0
}

var File_presence_proto protoreflect.FileDescriptor

var file_presence_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x23, 0x0a,
	0x11, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x4b, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x41, 0x74, 0x22,
	0x24, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x41, 0x74, 0x22, 0x32, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x4d, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x49, 0x73, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x50, 0x0a, 0x14, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x20, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x41,
	0x74, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x54, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63,
	0x65, 0x22, 0x91, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73,
	0x65, 0x65, 0x6e, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61,
	0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x41, 0x74, 0x32, 0xc0, 0x03, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65,
	0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x22, 0x2e, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x2e,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x61, 0x70, 0x70, 0x79, 0x4c, 0x61, 0x64, 0x79,
	0x53, 0x61, 0x75, 0x63, 0x65, 0x2f, 0x42, 0x65, 0x65, 0x68, 0x69, 0x76, 0x65, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_presence_proto_rawDescOnce sync.Once
	file_presence_proto_rawDescData = file_presence_proto_rawDesc
)

func file_presence_proto_rawDescGZIP() []byte {
	file_presence_proto_rawDescOnce.Do(func() {
		file_presence_proto_rawDescData = protoimpl.X.CompressGZIP(file_presence_proto_rawDescData)
	})
	return file_presence_proto_rawDescData
}

var file_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_presence_proto_goTypes = []interface{}{
	(*UserOnlineRequest)(nil),       // 0: presence.v1.UserOnlineRequest
	(*UserOnlineResponse)(nil),      // 1: presence.v1.UserOnlineResponse
	(*UserOfflineRequest)(nil),      // 2: presence.v1.UserOfflineRequest
	(*UserOfflineResponse)(nil),     // 3: presence.v1.UserOfflineResponse
	(*GetOnlineUsersRequest)(nil),   // 4: presence.v1.GetOnlineUsersRequest
	(*GetOnlineUsersResponse)(nil),  // 5: presence.v1.GetOnlineUsersResponse
	(*IsUserOnlineRequest)(nil),     // 6: presence.v1.IsUserOnlineRequest
	(*IsUserOnlineResponse)(nil),    // 7: presence.v1.IsUserOnlineResponse
	(*GetUserPresenceRequest)(nil),  // 8: presence.v1.GetUserPresenceRequest
	(*GetUserPresenceResponse)(nil), // 9: presence.v1.GetUserPresenceResponse
	(*UserPresenceInfo)(nil),        // 10: presence.v1.UserPresenceInfo
}
var file_presence_proto_depIdxs = []int32{
	10, // 0: presence.v1.GetOnlineUsersResponse.users:type_name -> presence.v1.UserPresenceInfo
	10, // 1: presence.v1.GetUserPresenceResponse.presence:type_name -> presence.v1.UserPresenceInfo
	0,  // 2: presence.v1.PresenceService.UserOnline:input_type -> presence.v1.UserOnlineRequest
	2,  // 3: presence.v1.PresenceService.UserOffline:input_type -> presence.v1.UserOfflineRequest
	4,  // 4: presence.v1.PresenceService.GetOnlineUsers:input_type -> presence.v1.GetOnlineUsersRequest
	6,  // 5: presence.v1.PresenceService.IsUserOnline:input_type -> presence.v1.IsUserOnlineRequest
	8,  // 6: presence.v1.PresenceService.GetUserPresence:input_type -> presence.v1.GetUserPresenceRequest
	1,  // 7: presence.v1.PresenceService.UserOnline:output_type -> presence.v1.UserOnlineResponse
	3,  // 8: presence.v1.PresenceService.UserOffline:output_type -> presence.v1.UserOfflineResponse
	5,  // 9: presence.v1.PresenceService.GetOnlineUsers:output_type -> presence.v1.GetOnlineUsersResponse
	7,  // 10: presence.v1.PresenceService.IsUserOnline:output_type -> presence.v1.IsUserOnlineResponse
	9,  // 11: presence.v1.PresenceService.GetUserPresence:output_type -> presence.v1.GetUserPresenceResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_presence_proto_init() }
func file_presence_proto_init() {
	if File_presence_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_presence_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfflineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOfflineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnlineUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnlineUsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsUserOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsUserOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPresenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPresenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_presence_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPresenceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_presence_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_proto_goTypes,
		DependencyIndexes: file_presence_proto_depIdxs,
		MessageInfos:      file_presence_proto_msgTypes,
	}.Build()
	File_presence_proto = out.File
	file_presence_proto_rawDesc = nil
	file_presence_proto_goTypes = nil
	file_presence_proto_depIdxs = nil
}
