// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: conversation.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/services/conversation/internal/logic"
	"github.com/HappyLadySauce/Beehive/services/conversation/internal/svc"
	"github.com/HappyLadySauce/Beehive/services/conversation/pb"
)

type ConversationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb_conversationpb.UnimplementedConversationServiceServer
}

func NewConversationServiceServer(svcCtx *svc.ServiceContext) *ConversationServiceServer {
	return &ConversationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ConversationServiceServer) CreateConversation(ctx context.Context, in *pb_conversationpb.CreateConversationRequest) (*pb_conversationpb.CreateConversationResponse, error) {
	l := logic.NewCreateConversationLogic(ctx, s.svcCtx)
	return l.CreateConversation(in)
}

func (s *ConversationServiceServer) AddMember(ctx context.Context, in *pb_conversationpb.AddMemberRequest) (*pb_conversationpb.AddMemberResponse, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

func (s *ConversationServiceServer) RemoveMember(ctx context.Context, in *pb_conversationpb.RemoveMemberRequest) (*pb_conversationpb.RemoveMemberResponse, error) {
	l := logic.NewRemoveMemberLogic(ctx, s.svcCtx)
	return l.RemoveMember(in)
}

func (s *ConversationServiceServer) ListUserConversations(ctx context.Context, in *pb_conversationpb.ListUserConversationsRequest) (*pb_conversationpb.ListUserConversationsResponse, error) {
	l := logic.NewListUserConversationsLogic(ctx, s.svcCtx)
	return l.ListUserConversations(in)
}

func (s *ConversationServiceServer) GetConversation(ctx context.Context, in *pb_conversationpb.GetConversationRequest) (*pb_conversationpb.GetConversationResponse, error) {
	l := logic.NewGetConversationLogic(ctx, s.svcCtx)
	return l.GetConversation(in)
}

func (s *ConversationServiceServer) ListMembers(ctx context.Context, in *pb_conversationpb.ListMembersRequest) (*pb_conversationpb.ListMembersResponse, error) {
	l := logic.NewListMembersLogic(ctx, s.svcCtx)
	return l.ListMembers(in)
}
