// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: conversation.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/services/conversation/internal/logic"
	"github.com/HappyLadySauce/Beehive/services/conversation/internal/svc"
	"github.com/HappyLadySauce/Beehive/services/conversation/pb"
)

type ConversationServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedConversationServiceServer
}

func NewConversationServiceServer(svcCtx *svc.ServiceContext) *ConversationServiceServer {
	return &ConversationServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ConversationServiceServer) CreateConversation(ctx context.Context, in *pb.CreateConversationRequest) (*pb.CreateConversationResponse, error) {
	l := logic.NewCreateConversationLogic(ctx, s.svcCtx)
	return l.CreateConversation(in)
}

func (s *ConversationServiceServer) AddMember(ctx context.Context, in *pb.AddMemberRequest) (*pb.AddMemberResponse, error) {
	l := logic.NewAddMemberLogic(ctx, s.svcCtx)
	return l.AddMember(in)
}

func (s *ConversationServiceServer) RemoveMember(ctx context.Context, in *pb.RemoveMemberRequest) (*pb.RemoveMemberResponse, error) {
	l := logic.NewRemoveMemberLogic(ctx, s.svcCtx)
	return l.RemoveMember(in)
}

func (s *ConversationServiceServer) ListUserConversations(ctx context.Context, in *pb.ListUserConversationsRequest) (*pb.ListUserConversationsResponse, error) {
	l := logic.NewListUserConversationsLogic(ctx, s.svcCtx)
	return l.ListUserConversations(in)
}

func (s *ConversationServiceServer) GetConversation(ctx context.Context, in *pb.GetConversationRequest) (*pb.GetConversationResponse, error) {
	l := logic.NewGetConversationLogic(ctx, s.svcCtx)
	return l.GetConversation(in)
}

func (s *ConversationServiceServer) ListMembers(ctx context.Context, in *pb.ListMembersRequest) (*pb.ListMembersResponse, error) {
	l := logic.NewListMembersLogic(ctx, s.svcCtx)
	return l.ListMembers(in)
}

func (s *ConversationServiceServer) FindOrCreateSingleConversation(ctx context.Context, in *pb.FindOrCreateSingleConversationRequest) (*pb.FindOrCreateSingleConversationResponse, error) {
	l := logic.NewFindOrCreateSingleConversationLogic(ctx, s.svcCtx)
	return l.FindOrCreateSingleConversation(in)
}

func (s *ConversationServiceServer) ApplyJoinGroup(ctx context.Context, in *pb.ApplyJoinGroupRequest) (*pb.ApplyJoinGroupResponse, error) {
	l := logic.NewApplyJoinGroupLogic(ctx, s.svcCtx)
	return l.ApplyJoinGroup(in)
}

func (s *ConversationServiceServer) ListJoinRequests(ctx context.Context, in *pb.ListJoinRequestsRequest) (*pb.ListJoinRequestsResponse, error) {
	l := logic.NewListJoinRequestsLogic(ctx, s.svcCtx)
	return l.ListJoinRequests(in)
}

func (s *ConversationServiceServer) ApproveJoinRequest(ctx context.Context, in *pb.ApproveJoinRequestRequest) (*pb.ApproveJoinRequestResponse, error) {
	l := logic.NewApproveJoinRequestLogic(ctx, s.svcCtx)
	return l.ApproveJoinRequest(in)
}

func (s *ConversationServiceServer) DeclineJoinRequest(ctx context.Context, in *pb.DeclineJoinRequestRequest) (*pb.DeclineJoinRequestResponse, error) {
	l := logic.NewDeclineJoinRequestLogic(ctx, s.svcCtx)
	return l.DeclineJoinRequest(in)
}
