// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Conversation struct {
	ConversationId int64                `json:"conversation_id"`
	Type           int32                `json:"type"`
	Name           string               `json:"name"`
	Avatar         string               `json:"avatar"`
	LastMessage    string               `json:"last_message"`
	LastMessageAt  int64                `json:"last_message_at"`
	UnreadCount    int32                `json:"unread_count"`
	Members        []ConversationMember `json:"members"`
}

type ConversationMember struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     int32  `json:"role"`
}

type CreateConversationReq struct {
	Type      int32   `json:"type" validate:"required,oneof=1 2"`
	Name      string  `json:"name,optional"`
	MemberIds []int64 `json:"member_ids" validate:"required,min=1"`
}

type CreateConversationResp struct {
	ConversationId int64 `json:"conversation_id"`
}

type DeleteFriendReq struct {
	FriendId int64 `path:"friend_id"`
}

type DeleteFriendResp struct {
	Success bool `json:"success"`
}

type Friend struct {
	UserId    int64  `json:"user_id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Remark    string `json:"remark"`
	Online    bool   `json:"online"`
	CreatedAt int64  `json:"created_at"`
}

type FriendRequest struct {
	RequestId  int64    `json:"request_id"`
	FromUserId int64    `json:"from_user_id"`
	FromUser   UserInfo `json:"from_user"`
	Message    string   `json:"message"`
	Status     int32    `json:"status"`
	CreatedAt  int64    `json:"created_at"`
}

type GetConversationDetailReq struct {
	ConversationId int64 `path:"conversation_id"`
}

type GetConversationsResp struct {
	Conversations []Conversation `json:"conversations"`
}

type GetFriendRequestsResp struct {
	Requests []FriendRequest `json:"requests"`
}

type GetFriendsResp struct {
	Friends []Friend `json:"friends"`
}

type GetMessagesReq struct {
	ConversationId int64 `path:"conversation_id"`
	BeforeId       int64 `form:"before_id,optional"`
	Limit          int32 `form:"limit,default=50"`
}

type GetMessagesResp struct {
	Messages []Message `json:"messages"`
	HasMore  bool      `json:"has_more"`
}

type GetUserInfoReq struct {
	UserId int64 `path:"user_id"`
}

type HandleFriendRequestReq struct {
	RequestId int64 `json:"request_id" validate:"required"`
	Accept    bool  `json:"accept"`
}

type HandleFriendRequestResp struct {
	Success bool `json:"success"`
}

type LoginReq struct {
	Account  string `json:"account" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Token    string `json:"token"`
}

type MarkReadReq struct {
	ConversationId int64 `json:"conversation_id"`
}

type MarkReadResp struct {
	Success bool `json:"success"`
}

type Message struct {
	MessageId      int64  `json:"message_id"`
	ConversationId int64  `json:"conversation_id"`
	SenderId       int64  `json:"sender_id"`
	SenderName     string `json:"sender_name"`
	SenderAvatar   string `json:"sender_avatar"`
	ContentType    int32  `json:"content_type"`
	Content        string `json:"content"`
	ExtraData      string `json:"extra_data,optional"`
	Status         int32  `json:"status"`
	CreatedAt      int64  `json:"created_at"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=50"`
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6"`
	Code     string `json:"code" validate:"required,len=6"`
}

type RegisterResp struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type SearchMessagesReq struct {
	Keyword        string `form:"keyword" validate:"required"`
	ConversationId int64  `form:"conversation_id,optional"`
	Page           int32  `form:"page,default=1"`
	PageSize       int32  `form:"page_size,default=20"`
}

type SearchMessagesResp struct {
	Messages []Message `json:"messages"`
	Total    int64     `json:"total"`
	Page     int32     `json:"page"`
	PageSize int32     `json:"page_size"`
}

type SendCodeReq struct {
	Email   string `json:"email" validate:"required,email"`
	Purpose string `json:"purpose" validate:"required,oneof=register reset_password"`
}

type SendCodeResp struct {
	Success bool `json:"success"`
}

type SendFriendRequestReq struct {
	ToUserId int64  `json:"to_user_id" validate:"required"`
	Message  string `json:"message,optional"`
}

type SendFriendRequestResp struct {
	RequestId int64 `json:"request_id"`
}

type UpdateUserInfoReq struct {
	Nickname  string `json:"nickname,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
}

type UpdateUserInfoResp struct {
	Success bool `json:"success"`
}

type UploadFileResp struct {
	FileId   int64  `json:"file_id"`
	FileUrl  string `json:"file_url"`
	FileHash string `json:"file_hash"`
}

type UserInfo struct {
	UserId      int64  `json:"user_id"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	Status      int32  `json:"status"`
	Online      bool   `json:"online"`
	LastLoginAt int64  `json:"last_login_at"`
	CreatedAt   int64  `json:"created_at"`
}
