// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: auth.proto

package authservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/services/auth/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest          = pb_authpb.LoginRequest
	LoginResponse         = pb_authpb.LoginResponse
	LogoutRequest         = pb_authpb.LogoutRequest
	LogoutResponse        = pb_authpb.LogoutResponse
	TokenLoginRequest     = pb_authpb.TokenLoginRequest
	ValidateTokenRequest  = pb_authpb.ValidateTokenRequest
	ValidateTokenResponse = pb_authpb.ValidateTokenResponse

	AuthService interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		TokenLogin(ctx context.Context, in *TokenLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb_authpb.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuthService) TokenLogin(ctx context.Context, in *TokenLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb_authpb.NewAuthServiceClient(m.cli.Conn())
	return client.TokenLogin(ctx, in, opts...)
}

func (m *defaultAuthService) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	client := pb_authpb.NewAuthServiceClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := pb_authpb.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}
