// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse            = user.CommonResponse
	GetUserInfoRequest        = user.GetUserInfoRequest
	GetUsersByIdsRequest      = user.GetUsersByIdsRequest
	LoginRequest              = user.LoginRequest
	LoginResponse             = user.LoginResponse
	RegisterRequest           = user.RegisterRequest
	RegisterResponse          = user.RegisterResponse
	SendCodeRequest           = user.SendCodeRequest
	UpdateOnlineStatusRequest = user.UpdateOnlineStatusRequest
	UpdateUserInfoRequest     = user.UpdateUserInfoRequest
	UserInfoResponse          = user.UserInfoResponse
	UsersResponse             = user.UsersResponse
	VerifyCodeRequest         = user.VerifyCodeRequest
	VerifyPasswordRequest     = user.VerifyPasswordRequest
	VerifyPasswordResponse    = user.VerifyPasswordResponse

	UserService interface {
		// 用户注册
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 用户登录
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		// 批量获取用户信息
		GetUsersByIds(ctx context.Context, in *GetUsersByIdsRequest, opts ...grpc.CallOption) (*UsersResponse, error)
		// 更新用户信息
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 发送邮箱验证码
		SendVerificationCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 验证邮箱验证码
		VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 更新在线状态
		UpdateOnlineStatus(ctx context.Context, in *UpdateOnlineStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 校验密码
		VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 用户注册
func (m *defaultUserService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 用户登录
func (m *defaultUserService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 批量获取用户信息
func (m *defaultUserService) GetUsersByIds(ctx context.Context, in *GetUsersByIdsRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.GetUsersByIds(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUserService) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

// 发送邮箱验证码
func (m *defaultUserService) SendVerificationCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.SendVerificationCode(ctx, in, opts...)
}

// 验证邮箱验证码
func (m *defaultUserService) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.VerifyCode(ctx, in, opts...)
}

// 更新在线状态
func (m *defaultUserService) UpdateOnlineStatus(ctx context.Context, in *UpdateOnlineStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.UpdateOnlineStatus(ctx, in, opts...)
}

// 校验密码
func (m *defaultUserService) VerifyPassword(ctx context.Context, in *VerifyPasswordRequest, opts ...grpc.CallOption) (*VerifyPasswordResponse, error) {
	client := user.NewUserServiceClient(m.cli.Conn())
	return client.VerifyPassword(ctx, in, opts...)
}
