// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chat.proto

package chatservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-chat/chat"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMembersRequest             = chat.AddMembersRequest
	CheckMemberRequest            = chat.CheckMemberRequest
	CheckMemberResponse           = chat.CheckMemberResponse
	CommonResponse                = chat.CommonResponse
	ConversationDetailResponse    = chat.ConversationDetailResponse
	ConversationInfo              = chat.ConversationInfo
	ConversationsResponse         = chat.ConversationsResponse
	CreateConversationRequest     = chat.CreateConversationRequest
	CreateConversationResponse    = chat.CreateConversationResponse
	GetConversationDetailRequest  = chat.GetConversationDetailRequest
	GetConversationsRequest       = chat.GetConversationsRequest
	MarkReadRequest               = chat.MarkReadRequest
	MemberInfo                    = chat.MemberInfo
	RemoveMembersRequest          = chat.RemoveMembersRequest
	UpdateConversationInfoRequest = chat.UpdateConversationInfoRequest
	UpdateUnreadCountRequest      = chat.UpdateUnreadCountRequest

	ChatService interface {
		// 创建会话
		CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error)
		// 获取会话列表
		GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*ConversationsResponse, error)
		// 获取会话详情
		GetConversationDetail(ctx context.Context, in *GetConversationDetailRequest, opts ...grpc.CallOption) (*ConversationDetailResponse, error)
		// 添加会话成员
		AddMembers(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 移除会话成员
		RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 更新未读数
		UpdateUnreadCount(ctx context.Context, in *UpdateUnreadCountRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 标记已读
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 更新会话信息
		UpdateConversationInfo(ctx context.Context, in *UpdateConversationInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 检查用户是否在会话中
		CheckMember(ctx context.Context, in *CheckMemberRequest, opts ...grpc.CallOption) (*CheckMemberResponse, error)
	}

	defaultChatService struct {
		cli zrpc.Client
	}
)

func NewChatService(cli zrpc.Client) ChatService {
	return &defaultChatService{
		cli: cli,
	}
}

// 创建会话
func (m *defaultChatService) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.CreateConversation(ctx, in, opts...)
}

// 获取会话列表
func (m *defaultChatService) GetConversations(ctx context.Context, in *GetConversationsRequest, opts ...grpc.CallOption) (*ConversationsResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

// 获取会话详情
func (m *defaultChatService) GetConversationDetail(ctx context.Context, in *GetConversationDetailRequest, opts ...grpc.CallOption) (*ConversationDetailResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.GetConversationDetail(ctx, in, opts...)
}

// 添加会话成员
func (m *defaultChatService) AddMembers(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.AddMembers(ctx, in, opts...)
}

// 移除会话成员
func (m *defaultChatService) RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.RemoveMembers(ctx, in, opts...)
}

// 更新未读数
func (m *defaultChatService) UpdateUnreadCount(ctx context.Context, in *UpdateUnreadCountRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.UpdateUnreadCount(ctx, in, opts...)
}

// 标记已读
func (m *defaultChatService) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

// 更新会话信息
func (m *defaultChatService) UpdateConversationInfo(ctx context.Context, in *UpdateConversationInfoRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.UpdateConversationInfo(ctx, in, opts...)
}

// 检查用户是否在会话中
func (m *defaultChatService) CheckMember(ctx context.Context, in *CheckMemberRequest, opts ...grpc.CallOption) (*CheckMemberResponse, error) {
	client := chat.NewChatServiceClient(m.cli.Conn())
	return client.CheckMember(ctx, in, opts...)
}
