// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// 认证中间件已接入：除 /admin/healthz 外均需 Bearer Token，见 docs/API/admin-http-api.md。

package handler

import (
	"net/http"

	admin "github.com/HappyLadySauce/Beehive/services/adminapi/internal/handler/admin"
	"github.com/HappyLadySauce/Beehive/services/adminapi/internal/middleware"
	"github.com/HappyLadySauce/Beehive/services/adminapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 健康检查无需认证
	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/healthz", Handler: admin.HealthHandler(serverCtx)},
		},
		rest.WithPrefix("/admin"),
	)

	// 其余路由需认证：Authorization: Bearer <token>
	protected := []rest.Route{
		{Method: http.MethodGet, Path: "/config", Handler: admin.ListConfigHandler(serverCtx)},
		{Method: http.MethodPut, Path: "/config/:key", Handler: admin.PutConfigHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/conversations", Handler: admin.ListConversationsHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/conversations/:id", Handler: admin.GetConversationHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/conversations/:id/members", Handler: admin.ListConversationMembersHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/conversations/:id/messages", Handler: admin.ListConversationMessagesHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/ops/health", Handler: admin.OpsHealthHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/ops/queues", Handler: admin.OpsQueuesHandler(serverCtx)},
		{Method: http.MethodPost, Path: "/ops/replay", Handler: admin.OpsReplayHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/users", Handler: admin.ListUsersHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/users/:id", Handler: admin.GetUserHandler(serverCtx)},
		{Method: http.MethodPost, Path: "/users/:id/ban", Handler: admin.BanUserHandler(serverCtx)},
		{Method: http.MethodPost, Path: "/users/:id/kick", Handler: admin.KickUserHandler(serverCtx)},
		{Method: http.MethodGet, Path: "/users/:id/sessions", Handler: admin.GetUserSessionsHandler(serverCtx)},
		{Method: http.MethodPost, Path: "/users/:id/unban", Handler: admin.UnbanUserHandler(serverCtx)},
	}
	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{middleware.AuthMiddleware(serverCtx)}, protected...),
		rest.WithPrefix("/admin"),
	)
}
