// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// 认证与权限：除 /admin/healthz 外需 Bearer Token + 按路由 CheckPermission，见 docs/API/admin-http-api.md。

package handler

import (
	"net/http"

	admin "github.com/HappyLadySauce/Beehive/services/adminapi/internal/handler/admin"
	"github.com/HappyLadySauce/Beehive/services/adminapi/internal/middleware"
	"github.com/HappyLadySauce/Beehive/services/adminapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// 健康检查无需认证
	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/healthz", Handler: admin.HealthHandler(serverCtx)},
		},
		rest.WithPrefix("/admin"),
	)

	authThenPerm := func(permission string) []rest.Middleware {
		return []rest.Middleware{
			middleware.AuthMiddleware(serverCtx),
			middleware.PermissionMiddleware(serverCtx, permission),
		}
	}

	// admin.user.read（仅读：列表、详情、会话列表）
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.user.read"), []rest.Route{
			{Method: http.MethodGet, Path: "/users", Handler: admin.ListUsersHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/users/:id", Handler: admin.GetUserHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/users/:id/sessions", Handler: admin.GetUserSessionsHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
	// admin.user.ban（用户管控：踢下线、封禁、解封）
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.user.ban"), []rest.Route{
			{Method: http.MethodPost, Path: "/users/:id/kick", Handler: admin.KickUserHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/users/:id/ban", Handler: admin.BanUserHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/users/:id/unban", Handler: admin.UnbanUserHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
	// admin.conversation.read
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.conversation.read"), []rest.Route{
			{Method: http.MethodGet, Path: "/conversations", Handler: admin.ListConversationsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/conversations/:id", Handler: admin.GetConversationHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/conversations/:id/members", Handler: admin.ListConversationMembersHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
	// admin.message.read
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.message.read"), []rest.Route{
			{Method: http.MethodGet, Path: "/conversations/:id/messages", Handler: admin.ListConversationMessagesHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
	// admin.config.read
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.config.read"), []rest.Route{
			{Method: http.MethodGet, Path: "/config", Handler: admin.ListConfigHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
	// admin.config.write
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.config.write"), []rest.Route{
			{Method: http.MethodPut, Path: "/config/:key", Handler: admin.PutConfigHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
	// admin.ops.use
	server.AddRoutes(
		rest.WithMiddlewares(authThenPerm("admin.ops.use"), []rest.Route{
			{Method: http.MethodGet, Path: "/ops/health", Handler: admin.OpsHealthHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/ops/queues", Handler: admin.OpsQueuesHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/ops/replay", Handler: admin.OpsReplayHandler(serverCtx)},
		}...),
		rest.WithPrefix("/admin"),
	)
}
