// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/services/user/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddContactRequest    = pb.AddContactRequest
	AddContactResponse   = pb.AddContactResponse
	BatchGetUsersRequest = pb.BatchGetUsersRequest
	BatchGetUsersResponse = pb.BatchGetUsersResponse
	GetUserRequest       = pb.GetUserRequest
	GetUserResponse      = pb.GetUserResponse
	GetUserByUsernameRequest  = pb.GetUserByUsernameRequest
	ListContactsRequest  = pb.ListContactsRequest
	ListContactsResponse = pb.ListContactsResponse
	RemoveContactRequest  = pb.RemoveContactRequest
	RemoveContactResponse = pb.RemoveContactResponse
	UpdateUserRequest     = pb.UpdateUserRequest
	UpdateUserResponse    = pb.UpdateUserResponse
	User                  = pb.User

	CreateContactRequestRequest  = pb.CreateContactRequestRequest
	CreateContactRequestResponse = pb.CreateContactRequestResponse
	ListContactRequestsRequest   = pb.ListContactRequestsRequest
	ListContactRequestsResponse = pb.ListContactRequestsResponse
	AcceptContactRequestRequest  = pb.AcceptContactRequestRequest
	AcceptContactRequestResponse = pb.AcceptContactRequestResponse
	DeclineContactRequestRequest = pb.DeclineContactRequestRequest
	DeclineContactRequestResponse = pb.DeclineContactRequestResponse

	UserService interface {
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
		AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error)
		ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
		RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*RemoveContactResponse, error)
		CreateContactRequest(ctx context.Context, in *CreateContactRequestRequest, opts ...grpc.CallOption) (*CreateContactRequestResponse, error)
		ListContactRequests(ctx context.Context, in *ListContactRequestsRequest, opts ...grpc.CallOption) (*ListContactRequestsResponse, error)
		AcceptContactRequest(ctx context.Context, in *AcceptContactRequestRequest, opts ...grpc.CallOption) (*AcceptContactRequestResponse, error)
		DeclineContactRequest(ctx context.Context, in *DeclineContactRequestRequest, opts ...grpc.CallOption) (*DeclineContactRequestResponse, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUserService) GetUserByUsername(ctx context.Context, in *GetUserByUsernameRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, in, opts...)
}

func (m *defaultUserService) BatchGetUsers(ctx context.Context, in *BatchGetUsersRequest, opts ...grpc.CallOption) (*BatchGetUsersResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.BatchGetUsers(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserService) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.AddContact(ctx, in, opts...)
}

func (m *defaultUserService) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ListContacts(ctx, in, opts...)
}

func (m *defaultUserService) RemoveContact(ctx context.Context, in *RemoveContactRequest, opts ...grpc.CallOption) (*RemoveContactResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.RemoveContact(ctx, in, opts...)
}

func (m *defaultUserService) CreateContactRequest(ctx context.Context, in *CreateContactRequestRequest, opts ...grpc.CallOption) (*CreateContactRequestResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.CreateContactRequest(ctx, in, opts...)
}

func (m *defaultUserService) ListContactRequests(ctx context.Context, in *ListContactRequestsRequest, opts ...grpc.CallOption) (*ListContactRequestsResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.ListContactRequests(ctx, in, opts...)
}

func (m *defaultUserService) AcceptContactRequest(ctx context.Context, in *AcceptContactRequestRequest, opts ...grpc.CallOption) (*AcceptContactRequestResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.AcceptContactRequest(ctx, in, opts...)
}

func (m *defaultUserService) DeclineContactRequest(ctx context.Context, in *DeclineContactRequestRequest, opts ...grpc.CallOption) (*DeclineContactRequestResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.DeclineContactRequest(ctx, in, opts...)
}
