// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-message/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse             = message.CommonResponse
	GetMessageDetailRequest    = message.GetMessageDetailRequest
	GetMessagesRequest         = message.GetMessagesRequest
	MessageInfo                = message.MessageInfo
	MessagesResponse           = message.MessagesResponse
	SendMessageRequest         = message.SendMessageRequest
	SendMessageResponse        = message.SendMessageResponse
	UpdateMessageStatusRequest = message.UpdateMessageStatusRequest

	MessageService interface {
		// 发送消息
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		// 获取历史消息
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error)
		// 更新消息状态
		UpdateMessageStatus(ctx context.Context, in *UpdateMessageStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 获取消息详情
		GetMessageDetail(ctx context.Context, in *GetMessageDetailRequest, opts ...grpc.CallOption) (*MessageInfo, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

// 发送消息
func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// 获取历史消息
func (m *defaultMessageService) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*MessagesResponse, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

// 更新消息状态
func (m *defaultMessageService) UpdateMessageStatus(ctx context.Context, in *UpdateMessageStatusRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.UpdateMessageStatus(ctx, in, opts...)
}

// 获取消息详情
func (m *defaultMessageService) GetMessageDetail(ctx context.Context, in *GetMessageDetailRequest, opts ...grpc.CallOption) (*MessageInfo, error) {
	client := message.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessageDetail(ctx, in, opts...)
}
