// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/beehive-friend/v1/friend.proto

package friend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送好友申请请求
type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{0}
}

func (x *SendFriendRequestRequest) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送好友申请响应
type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// 处理好友申请请求
type HandleFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Accept        bool                   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestRequest) Reset() {
	*x = HandleFriendRequestRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestRequest) ProtoMessage() {}

func (x *HandleFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{2}
}

func (x *HandleFriendRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// 获取好友申请列表请求
type GetFriendRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendRequestsRequest) Reset() {
	*x = GetFriendRequestsRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendRequestsRequest) ProtoMessage() {}

func (x *GetFriendRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{3}
}

func (x *GetFriendRequestsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 好友申请列表响应
type FriendRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestInfo   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestsResponse) Reset() {
	*x = FriendRequestsResponse{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestsResponse) ProtoMessage() {}

func (x *FriendRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestsResponse.ProtoReflect.Descriptor instead.
func (*FriendRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{4}
}

func (x *FriendRequestsResponse) GetRequests() []*FriendRequestInfo {
	if x != nil {
		return x.Requests
	}
	return nil
}

// 好友申请信息
type FriendRequestInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromUserId    int64                  `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestInfo) Reset() {
	*x = FriendRequestInfo{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestInfo) ProtoMessage() {}

func (x *FriendRequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestInfo.ProtoReflect.Descriptor instead.
func (*FriendRequestInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{5}
}

func (x *FriendRequestInfo) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FriendRequestInfo) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *FriendRequestInfo) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FriendRequestInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequestInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequestInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 获取好友列表请求
type GetFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendsRequest) Reset() {
	*x = GetFriendsRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendsRequest) ProtoMessage() {}

func (x *GetFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetFriendsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{6}
}

func (x *GetFriendsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 好友列表响应
type FriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*FriendInfo          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendsResponse) Reset() {
	*x = FriendsResponse{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendsResponse) ProtoMessage() {}

func (x *FriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendsResponse.ProtoReflect.Descriptor instead.
func (*FriendsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{7}
}

func (x *FriendsResponse) GetFriends() []*FriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

// 好友信息
type FriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{8}
}

func (x *FriendInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FriendInfo) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 删除好友请求
type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFriendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 检查是否为好友请求
type IsFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendRequest) Reset() {
	*x = IsFriendRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendRequest) ProtoMessage() {}

func (x *IsFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendRequest.ProtoReflect.Descriptor instead.
func (*IsFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{10}
}

func (x *IsFriendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IsFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

// 检查是否为好友响应
type IsFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFriend      bool                   `protobuf:"varint,1,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFriendResponse) Reset() {
	*x = IsFriendResponse{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFriendResponse) ProtoMessage() {}

func (x *IsFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFriendResponse.ProtoReflect.Descriptor instead.
func (*IsFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{11}
}

func (x *IsFriendResponse) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

// 更新好友备注请求
type UpdateFriendRemarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendRemarkRequest) Reset() {
	*x = UpdateFriendRemarkRequest{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendRemarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendRemarkRequest) ProtoMessage() {}

func (x *UpdateFriendRemarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendRemarkRequest.ProtoReflect.Descriptor instead.
func (*UpdateFriendRemarkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFriendRemarkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateFriendRemarkRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *UpdateFriendRemarkRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_friend_v1_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP(), []int{13}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_beehive_friend_v1_friend_proto protoreflect.FileDescriptor

const file_api_proto_beehive_friend_v1_friend_proto_rawDesc = "" +
	"\n" +
	"(api/proto/beehive-friend/v1/friend.proto\x12\x06friend\"t\n" +
	"\x18SendFriendRequestRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\":\n" +
	"\x19SendFriendRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"l\n" +
	"\x1aHandleFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\"3\n" +
	"\x18GetFriendRequestsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"O\n" +
	"\x16FriendRequestsResponse\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.friend.FriendRequestInfoR\brequests\"\xc3\x01\n" +
	"\x11FriendRequestInfo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\",\n" +
	"\x11GetFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"?\n" +
	"\x0fFriendsResponse\x12,\n" +
	"\afriends\x18\x01 \x03(\v2\x12.friend.FriendInfoR\afriends\"y\n" +
	"\n" +
	"FriendInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"K\n" +
	"\x13DeleteFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"G\n" +
	"\x0fIsFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"/\n" +
	"\x10IsFriendResponse\x12\x1b\n" +
	"\tis_friend\x18\x01 \x01(\bR\bisFriend\"i\n" +
	"\x19UpdateFriendRemarkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"D\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xaa\x04\n" +
	"\rFriendService\x12X\n" +
	"\x11SendFriendRequest\x12 .friend.SendFriendRequestRequest\x1a!.friend.SendFriendRequestResponse\x12Q\n" +
	"\x13HandleFriendRequest\x12\".friend.HandleFriendRequestRequest\x1a\x16.friend.CommonResponse\x12U\n" +
	"\x11GetFriendRequests\x12 .friend.GetFriendRequestsRequest\x1a\x1e.friend.FriendRequestsResponse\x12@\n" +
	"\n" +
	"GetFriends\x12\x19.friend.GetFriendsRequest\x1a\x17.friend.FriendsResponse\x12C\n" +
	"\fDeleteFriend\x12\x1b.friend.DeleteFriendRequest\x1a\x16.friend.CommonResponse\x12=\n" +
	"\bIsFriend\x12\x17.friend.IsFriendRequest\x1a\x18.friend.IsFriendResponse\x12O\n" +
	"\x12UpdateFriendRemark\x12!.friend.UpdateFriendRemarkRequest\x1a\x16.friend.CommonResponseB\n" +
	"Z\b./friendb\x06proto3"

var (
	file_api_proto_beehive_friend_v1_friend_proto_rawDescOnce sync.Once
	file_api_proto_beehive_friend_v1_friend_proto_rawDescData []byte
)

func file_api_proto_beehive_friend_v1_friend_proto_rawDescGZIP() []byte {
	file_api_proto_beehive_friend_v1_friend_proto_rawDescOnce.Do(func() {
		file_api_proto_beehive_friend_v1_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_beehive_friend_v1_friend_proto_rawDesc), len(file_api_proto_beehive_friend_v1_friend_proto_rawDesc)))
	})
	return file_api_proto_beehive_friend_v1_friend_proto_rawDescData
}

var file_api_proto_beehive_friend_v1_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_beehive_friend_v1_friend_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),   // 0: friend.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),  // 1: friend.SendFriendRequestResponse
	(*HandleFriendRequestRequest)(nil), // 2: friend.HandleFriendRequestRequest
	(*GetFriendRequestsRequest)(nil),   // 3: friend.GetFriendRequestsRequest
	(*FriendRequestsResponse)(nil),     // 4: friend.FriendRequestsResponse
	(*FriendRequestInfo)(nil),          // 5: friend.FriendRequestInfo
	(*GetFriendsRequest)(nil),          // 6: friend.GetFriendsRequest
	(*FriendsResponse)(nil),            // 7: friend.FriendsResponse
	(*FriendInfo)(nil),                 // 8: friend.FriendInfo
	(*DeleteFriendRequest)(nil),        // 9: friend.DeleteFriendRequest
	(*IsFriendRequest)(nil),            // 10: friend.IsFriendRequest
	(*IsFriendResponse)(nil),           // 11: friend.IsFriendResponse
	(*UpdateFriendRemarkRequest)(nil),  // 12: friend.UpdateFriendRemarkRequest
	(*CommonResponse)(nil),             // 13: friend.CommonResponse
}
var file_api_proto_beehive_friend_v1_friend_proto_depIdxs = []int32{
	5,  // 0: friend.FriendRequestsResponse.requests:type_name -> friend.FriendRequestInfo
	8,  // 1: friend.FriendsResponse.friends:type_name -> friend.FriendInfo
	0,  // 2: friend.FriendService.SendFriendRequest:input_type -> friend.SendFriendRequestRequest
	2,  // 3: friend.FriendService.HandleFriendRequest:input_type -> friend.HandleFriendRequestRequest
	3,  // 4: friend.FriendService.GetFriendRequests:input_type -> friend.GetFriendRequestsRequest
	6,  // 5: friend.FriendService.GetFriends:input_type -> friend.GetFriendsRequest
	9,  // 6: friend.FriendService.DeleteFriend:input_type -> friend.DeleteFriendRequest
	10, // 7: friend.FriendService.IsFriend:input_type -> friend.IsFriendRequest
	12, // 8: friend.FriendService.UpdateFriendRemark:input_type -> friend.UpdateFriendRemarkRequest
	1,  // 9: friend.FriendService.SendFriendRequest:output_type -> friend.SendFriendRequestResponse
	13, // 10: friend.FriendService.HandleFriendRequest:output_type -> friend.CommonResponse
	4,  // 11: friend.FriendService.GetFriendRequests:output_type -> friend.FriendRequestsResponse
	7,  // 12: friend.FriendService.GetFriends:output_type -> friend.FriendsResponse
	13, // 13: friend.FriendService.DeleteFriend:output_type -> friend.CommonResponse
	11, // 14: friend.FriendService.IsFriend:output_type -> friend.IsFriendResponse
	13, // 15: friend.FriendService.UpdateFriendRemark:output_type -> friend.CommonResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_beehive_friend_v1_friend_proto_init() }
func file_api_proto_beehive_friend_v1_friend_proto_init() {
	if File_api_proto_beehive_friend_v1_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_beehive_friend_v1_friend_proto_rawDesc), len(file_api_proto_beehive_friend_v1_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_beehive_friend_v1_friend_proto_goTypes,
		DependencyIndexes: file_api_proto_beehive_friend_v1_friend_proto_depIdxs,
		MessageInfos:      file_api_proto_beehive_friend_v1_friend_proto_msgTypes,
	}.Build()
	File_api_proto_beehive_friend_v1_friend_proto = out.File
	file_api_proto_beehive_friend_v1_friend_proto_goTypes = nil
	file_api_proto_beehive_friend_v1_friend_proto_depIdxs = nil
}
