// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package friendservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-friend/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CommonResponse             = friend.CommonResponse
	DeleteFriendRequest        = friend.DeleteFriendRequest
	FriendInfo                 = friend.FriendInfo
	FriendRequestInfo          = friend.FriendRequestInfo
	FriendRequestsResponse     = friend.FriendRequestsResponse
	FriendsResponse            = friend.FriendsResponse
	GetFriendRequestsRequest   = friend.GetFriendRequestsRequest
	GetFriendsRequest          = friend.GetFriendsRequest
	HandleFriendRequestRequest = friend.HandleFriendRequestRequest
	IsFriendRequest            = friend.IsFriendRequest
	IsFriendResponse           = friend.IsFriendResponse
	SendFriendRequestRequest   = friend.SendFriendRequestRequest
	SendFriendRequestResponse  = friend.SendFriendRequestResponse
	UpdateFriendRemarkRequest  = friend.UpdateFriendRemarkRequest

	FriendService interface {
		// 发送好友申请
		SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error)
		// 处理好友申请
		HandleFriendRequest(ctx context.Context, in *HandleFriendRequestRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 获取好友申请列表
		GetFriendRequests(ctx context.Context, in *GetFriendRequestsRequest, opts ...grpc.CallOption) (*FriendRequestsResponse, error)
		// 获取好友列表
		GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*FriendsResponse, error)
		// 删除好友
		DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*CommonResponse, error)
		// 检查是否为好友
		IsFriend(ctx context.Context, in *IsFriendRequest, opts ...grpc.CallOption) (*IsFriendResponse, error)
		// 更新好友备注
		UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	}

	defaultFriendService struct {
		cli zrpc.Client
	}
)

func NewFriendService(cli zrpc.Client) FriendService {
	return &defaultFriendService{
		cli: cli,
	}
}

// 发送好友申请
func (m *defaultFriendService) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.SendFriendRequest(ctx, in, opts...)
}

// 处理好友申请
func (m *defaultFriendService) HandleFriendRequest(ctx context.Context, in *HandleFriendRequestRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.HandleFriendRequest(ctx, in, opts...)
}

// 获取好友申请列表
func (m *defaultFriendService) GetFriendRequests(ctx context.Context, in *GetFriendRequestsRequest, opts ...grpc.CallOption) (*FriendRequestsResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.GetFriendRequests(ctx, in, opts...)
}

// 获取好友列表
func (m *defaultFriendService) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*FriendsResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.GetFriends(ctx, in, opts...)
}

// 删除好友
func (m *defaultFriendService) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

// 检查是否为好友
func (m *defaultFriendService) IsFriend(ctx context.Context, in *IsFriendRequest, opts ...grpc.CallOption) (*IsFriendResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.IsFriend(ctx, in, opts...)
}

// 更新好友备注
func (m *defaultFriendService) UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	client := friend.NewFriendServiceClient(m.cli.Conn())
	return client.UpdateFriendRemark(ctx, in, opts...)
}
