// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-friend/friend"
	"github.com/HappyLadySauce/Beehive/app/beehive-friend/internal/logic"
	"github.com/HappyLadySauce/Beehive/app/beehive-friend/internal/svc"
)

type FriendServiceServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServiceServer
}

func NewFriendServiceServer(svcCtx *svc.ServiceContext) *FriendServiceServer {
	return &FriendServiceServer{
		svcCtx: svcCtx,
	}
}

// 发送好友申请
func (s *FriendServiceServer) SendFriendRequest(ctx context.Context, in *friend.SendFriendRequestRequest) (*friend.SendFriendRequestResponse, error) {
	l := logic.NewSendFriendRequestLogic(ctx, s.svcCtx)
	return l.SendFriendRequest(in)
}

// 处理好友申请
func (s *FriendServiceServer) HandleFriendRequest(ctx context.Context, in *friend.HandleFriendRequestRequest) (*friend.CommonResponse, error) {
	l := logic.NewHandleFriendRequestLogic(ctx, s.svcCtx)
	return l.HandleFriendRequest(in)
}

// 获取好友申请列表
func (s *FriendServiceServer) GetFriendRequests(ctx context.Context, in *friend.GetFriendRequestsRequest) (*friend.FriendRequestsResponse, error) {
	l := logic.NewGetFriendRequestsLogic(ctx, s.svcCtx)
	return l.GetFriendRequests(in)
}

// 获取好友列表
func (s *FriendServiceServer) GetFriends(ctx context.Context, in *friend.GetFriendsRequest) (*friend.FriendsResponse, error) {
	l := logic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}

// 删除好友
func (s *FriendServiceServer) DeleteFriend(ctx context.Context, in *friend.DeleteFriendRequest) (*friend.CommonResponse, error) {
	l := logic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

// 检查是否为好友
func (s *FriendServiceServer) IsFriend(ctx context.Context, in *friend.IsFriendRequest) (*friend.IsFriendResponse, error) {
	l := logic.NewIsFriendLogic(ctx, s.svcCtx)
	return l.IsFriend(in)
}

// 更新好友备注
func (s *FriendServiceServer) UpdateFriendRemark(ctx context.Context, in *friend.UpdateFriendRemarkRequest) (*friend.CommonResponse, error) {
	l := logic.NewUpdateFriendRemarkLogic(ctx, s.svcCtx)
	return l.UpdateFriendRemark(in)
}
