// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: presence.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/services/presence/internal/logic"
	"github.com/HappyLadySauce/Beehive/services/presence/internal/svc"
	"github.com/HappyLadySauce/Beehive/services/presence/pb"
)

type PresenceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb_presencepb.UnimplementedPresenceServiceServer
}

func NewPresenceServiceServer(svcCtx *svc.ServiceContext) *PresenceServiceServer {
	return &PresenceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PresenceServiceServer) RegisterSession(ctx context.Context, in *pb_presencepb.RegisterSessionRequest) (*pb_presencepb.RegisterSessionResponse, error) {
	l := logic.NewRegisterSessionLogic(ctx, s.svcCtx)
	return l.RegisterSession(in)
}

func (s *PresenceServiceServer) UnregisterSession(ctx context.Context, in *pb_presencepb.UnregisterSessionRequest) (*pb_presencepb.UnregisterSessionResponse, error) {
	l := logic.NewUnregisterSessionLogic(ctx, s.svcCtx)
	return l.UnregisterSession(in)
}

func (s *PresenceServiceServer) RefreshSession(ctx context.Context, in *pb_presencepb.RefreshSessionRequest) (*pb_presencepb.RefreshSessionResponse, error) {
	l := logic.NewRefreshSessionLogic(ctx, s.svcCtx)
	return l.RefreshSession(in)
}

func (s *PresenceServiceServer) GetOnlineSessions(ctx context.Context, in *pb_presencepb.GetOnlineSessionsRequest) (*pb_presencepb.GetOnlineSessionsResponse, error) {
	l := logic.NewGetOnlineSessionsLogic(ctx, s.svcCtx)
	return l.GetOnlineSessions(in)
}

func (s *PresenceServiceServer) GetUserPresence(ctx context.Context, in *pb_presencepb.GetUserPresenceRequest) (*pb_presencepb.GetUserPresenceResponse, error) {
	l := logic.NewGetUserPresenceLogic(ctx, s.svcCtx)
	return l.GetUserPresence(in)
}
