// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/beehive-search/v1/search.proto

package search

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 搜索消息请求
type SearchMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Keyword        string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Page           int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchMessagesRequest) Reset() {
	*x = SearchMessagesRequest{}
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesRequest) ProtoMessage() {}

func (x *SearchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesRequest.ProtoReflect.Descriptor instead.
func (*SearchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMessagesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchMessagesRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SearchMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 搜索消息响应
type SearchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SearchMessageInfo   `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesResponse) Reset() {
	*x = SearchMessagesResponse{}
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesResponse) ProtoMessage() {}

func (x *SearchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesResponse.ProtoReflect.Descriptor instead.
func (*SearchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMessagesResponse) GetMessages() []*SearchMessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SearchMessagesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 搜索消息信息
type SearchMessageInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Highlight      string                 `protobuf:"bytes,5,opt,name=highlight,proto3" json:"highlight,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchMessageInfo) Reset() {
	*x = SearchMessageInfo{}
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessageInfo) ProtoMessage() {}

func (x *SearchMessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessageInfo.ProtoReflect.Descriptor instead.
func (*SearchMessageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMessageInfo) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SearchMessageInfo) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SearchMessageInfo) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SearchMessageInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchMessageInfo) GetHighlight() string {
	if x != nil {
		return x.Highlight
	}
	return ""
}

func (x *SearchMessageInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 索引消息请求
type IndexMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IndexMessageRequest) Reset() {
	*x = IndexMessageRequest{}
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMessageRequest) ProtoMessage() {}

func (x *IndexMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMessageRequest.ProtoReflect.Descriptor instead.
func (*IndexMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *IndexMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *IndexMessageRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *IndexMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *IndexMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IndexMessageRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 删除消息索引请求
type DeleteMessageIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageIndexRequest) Reset() {
	*x = DeleteMessageIndexRequest{}
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageIndexRequest) ProtoMessage() {}

func (x *DeleteMessageIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMessageIndexRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_beehive_search_v1_search_proto protoreflect.FileDescriptor

const file_api_proto_beehive_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"(api/proto/beehive-search/v1/search.proto\x12\x06search\"\xa4\x01\n" +
	"\x15SearchMessagesRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"e\n" +
	"\x16SearchMessagesResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.search.SearchMessageInfoR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xcf\x01\n" +
	"\x11SearchMessageInfo\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\thighlight\x18\x05 \x01(\tR\thighlight\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xb3\x01\n" +
	"\x13IndexMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\":\n" +
	"\x19DeleteMessageIndexRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"D\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf6\x01\n" +
	"\rSearchService\x12O\n" +
	"\x0eSearchMessages\x12\x1d.search.SearchMessagesRequest\x1a\x1e.search.SearchMessagesResponse\x12C\n" +
	"\fIndexMessage\x12\x1b.search.IndexMessageRequest\x1a\x16.search.CommonResponse\x12O\n" +
	"\x12DeleteMessageIndex\x12!.search.DeleteMessageIndexRequest\x1a\x16.search.CommonResponseB\n" +
	"Z\b./searchb\x06proto3"

var (
	file_api_proto_beehive_search_v1_search_proto_rawDescOnce sync.Once
	file_api_proto_beehive_search_v1_search_proto_rawDescData []byte
)

func file_api_proto_beehive_search_v1_search_proto_rawDescGZIP() []byte {
	file_api_proto_beehive_search_v1_search_proto_rawDescOnce.Do(func() {
		file_api_proto_beehive_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_beehive_search_v1_search_proto_rawDesc), len(file_api_proto_beehive_search_v1_search_proto_rawDesc)))
	})
	return file_api_proto_beehive_search_v1_search_proto_rawDescData
}

var file_api_proto_beehive_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_beehive_search_v1_search_proto_goTypes = []any{
	(*SearchMessagesRequest)(nil),     // 0: search.SearchMessagesRequest
	(*SearchMessagesResponse)(nil),    // 1: search.SearchMessagesResponse
	(*SearchMessageInfo)(nil),         // 2: search.SearchMessageInfo
	(*IndexMessageRequest)(nil),       // 3: search.IndexMessageRequest
	(*DeleteMessageIndexRequest)(nil), // 4: search.DeleteMessageIndexRequest
	(*CommonResponse)(nil),            // 5: search.CommonResponse
}
var file_api_proto_beehive_search_v1_search_proto_depIdxs = []int32{
	2, // 0: search.SearchMessagesResponse.messages:type_name -> search.SearchMessageInfo
	0, // 1: search.SearchService.SearchMessages:input_type -> search.SearchMessagesRequest
	3, // 2: search.SearchService.IndexMessage:input_type -> search.IndexMessageRequest
	4, // 3: search.SearchService.DeleteMessageIndex:input_type -> search.DeleteMessageIndexRequest
	1, // 4: search.SearchService.SearchMessages:output_type -> search.SearchMessagesResponse
	5, // 5: search.SearchService.IndexMessage:output_type -> search.CommonResponse
	5, // 6: search.SearchService.DeleteMessageIndex:output_type -> search.CommonResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_beehive_search_v1_search_proto_init() }
func file_api_proto_beehive_search_v1_search_proto_init() {
	if File_api_proto_beehive_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_beehive_search_v1_search_proto_rawDesc), len(file_api_proto_beehive_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_beehive_search_v1_search_proto_goTypes,
		DependencyIndexes: file_api_proto_beehive_search_v1_search_proto_depIdxs,
		MessageInfos:      file_api_proto_beehive_search_v1_search_proto_msgTypes,
	}.Build()
	File_api_proto_beehive_search_v1_search_proto = out.File
	file_api_proto_beehive_search_v1_search_proto_goTypes = nil
	file_api_proto_beehive_search_v1_search_proto_depIdxs = nil
}
