// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: edge.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/edge/edge"
	"github.com/HappyLadySauce/Beehive/edge/internal/logic"
	"github.com/HappyLadySauce/Beehive/edge/internal/svc"
)

type EdgeServer struct {
	svcCtx *svc.ServiceContext
	edge.UnimplementedEdgeServer
}

func NewEdgeServer(svcCtx *svc.ServiceContext) *EdgeServer {
	return &EdgeServer{
		svcCtx: svcCtx,
	}
}

func (s *EdgeServer) Ping(ctx context.Context, in *edge.Request) (*edge.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
