services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: beehive-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../../data/rabbitmq:/var/lib/rabbitmq
    networks:
      - beehive-net

networks:
  beehive-net:
    driver: bridge
