// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: search.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive/app/beehive-search/internal/logic"
	"github.com/HappyLadySauce/Beehive/app/beehive-search/internal/svc"
	"github.com/HappyLadySauce/Beehive/app/beehive-search/search"
)

type SearchServiceServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServiceServer
}

func NewSearchServiceServer(svcCtx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{
		svcCtx: svcCtx,
	}
}

// 搜索消息
func (s *SearchServiceServer) SearchMessages(ctx context.Context, in *search.SearchMessagesRequest) (*search.SearchMessagesResponse, error) {
	l := logic.NewSearchMessagesLogic(ctx, s.svcCtx)
	return l.SearchMessages(in)
}

// 索引消息
func (s *SearchServiceServer) IndexMessage(ctx context.Context, in *search.IndexMessageRequest) (*search.CommonResponse, error) {
	l := logic.NewIndexMessageLogic(ctx, s.svcCtx)
	return l.IndexMessage(in)
}

// 删除消息索引
func (s *SearchServiceServer) DeleteMessageIndex(ctx context.Context, in *search.DeleteMessageIndexRequest) (*search.CommonResponse, error) {
	l := logic.NewDeleteMessageIndexLogic(ctx, s.svcCtx)
	return l.DeleteMessageIndex(in)
}
