// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/beehive-chat/v1/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建会话请求
type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MemberIds     []int64                `protobuf:"varint,4,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConversationRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateConversationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConversationRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateConversationRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// 创建会话响应
type CreateConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConversationResponse) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

// 获取会话列表请求
type GetConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsRequest) Reset() {
	*x = GetConversationsRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsRequest) ProtoMessage() {}

func (x *GetConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsRequest.ProtoReflect.Descriptor instead.
func (*GetConversationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetConversationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 会话列表响应
type ConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ConversationInfo    `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationsResponse) Reset() {
	*x = ConversationsResponse{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationsResponse) ProtoMessage() {}

func (x *ConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationsResponse.ProtoReflect.Descriptor instead.
func (*ConversationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationsResponse) GetConversations() []*ConversationInfo {
	if x != nil {
		return x.Conversations
	}
	return nil
}

// 会话信息
type ConversationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Type           int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UnreadCount    int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	LastMessageAt  int64                  `protobuf:"varint,6,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationInfo) Reset() {
	*x = ConversationInfo{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationInfo) ProtoMessage() {}

func (x *ConversationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationInfo.ProtoReflect.Descriptor instead.
func (*ConversationInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationInfo) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ConversationInfo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConversationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConversationInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ConversationInfo) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationInfo) GetLastMessageAt() int64 {
	if x != nil {
		return x.LastMessageAt
	}
	return 0
}

// 获取会话详情请求
type GetConversationDetailRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationDetailRequest) Reset() {
	*x = GetConversationDetailRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationDetailRequest) ProtoMessage() {}

func (x *GetConversationDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationDetailRequest.ProtoReflect.Descriptor instead.
func (*GetConversationDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetConversationDetailRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *GetConversationDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 会话详情响应
type ConversationDetailResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Type           int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OwnerId        int64                  `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Members        []*MemberInfo          `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationDetailResponse) Reset() {
	*x = ConversationDetailResponse{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationDetailResponse) ProtoMessage() {}

func (x *ConversationDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationDetailResponse.ProtoReflect.Descriptor instead.
func (*ConversationDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationDetailResponse) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *ConversationDetailResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConversationDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConversationDetailResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ConversationDetailResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ConversationDetailResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

// 会话成员信息
type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MemberInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *MemberInfo) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

// 添加成员请求
type AddMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserIds        []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMembersRequest) Reset() {
	*x = AddMembersRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersRequest) ProtoMessage() {}

func (x *AddMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersRequest.ProtoReflect.Descriptor instead.
func (*AddMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *AddMembersRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *AddMembersRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 移除成员请求
type RemoveMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserIds        []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveMembersRequest) Reset() {
	*x = RemoveMembersRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersRequest) ProtoMessage() {}

func (x *RemoveMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersRequest.ProtoReflect.Descriptor instead.
func (*RemoveMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveMembersRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *RemoveMembersRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 更新未读数请求
type UpdateUnreadCountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Increment      int32                  `protobuf:"varint,3,opt,name=increment,proto3" json:"increment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUnreadCountRequest) Reset() {
	*x = UpdateUnreadCountRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUnreadCountRequest) ProtoMessage() {}

func (x *UpdateUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*UpdateUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUnreadCountRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *UpdateUnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUnreadCountRequest) GetIncrement() int32 {
	if x != nil {
		return x.Increment
	}
	return 0
}

// 标记已读请求
type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *MarkReadRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *MarkReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 更新会话信息请求
type UpdateConversationInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateConversationInfoRequest) Reset() {
	*x = UpdateConversationInfoRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationInfoRequest) ProtoMessage() {}

func (x *UpdateConversationInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateConversationInfoRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *UpdateConversationInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConversationInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 检查成员请求
type CheckMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckMemberRequest) Reset() {
	*x = CheckMemberRequest{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberRequest) ProtoMessage() {}

func (x *CheckMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberRequest.ProtoReflect.Descriptor instead.
func (*CheckMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *CheckMemberRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *CheckMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 检查成员响应
type CheckMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMemberResponse) Reset() {
	*x = CheckMemberResponse{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMemberResponse) ProtoMessage() {}

func (x *CheckMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMemberResponse.ProtoReflect.Descriptor instead.
func (*CheckMemberResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *CheckMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *CheckMemberResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_beehive_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_beehive_chat_v1_chat_proto protoreflect.FileDescriptor

const file_api_proto_beehive_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"$api/proto/beehive-chat/v1/chat.proto\x12\x04chat\"}\n" +
	"\x19CreateConversationRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x04 \x03(\x03R\tmemberIds\"E\n" +
	"\x1aCreateConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\"2\n" +
	"\x17GetConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"U\n" +
	"\x15ConversationsResponse\x12<\n" +
	"\rconversations\x18\x01 \x03(\v2\x16.chat.ConversationInfoR\rconversations\"\xc6\x01\n" +
	"\x10ConversationInfo\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\x12&\n" +
	"\x0flast_message_at\x18\x06 \x01(\x03R\rlastMessageAt\"`\n" +
	"\x1cGetConversationDetailRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xcc\x01\n" +
	"\x1aConversationDetailResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x03R\aownerId\x12*\n" +
	"\amembers\x18\x06 \x03(\v2\x10.chat.MemberInfoR\amembers\"V\n" +
	"\n" +
	"MemberInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\x03R\bjoinedAt\"W\n" +
	"\x11AddMembersRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\"Z\n" +
	"\x14RemoveMembersRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\"z\n" +
	"\x18UpdateUnreadCountRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tincrement\x18\x03 \x01(\x05R\tincrement\"S\n" +
	"\x0fMarkReadRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"t\n" +
	"\x1dUpdateConversationInfoRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"V\n" +
	"\x12CheckMemberRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"F\n" +
	"\x13CheckMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\"D\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\x05\n" +
	"\vChatService\x12W\n" +
	"\x12CreateConversation\x12\x1f.chat.CreateConversationRequest\x1a .chat.CreateConversationResponse\x12N\n" +
	"\x10GetConversations\x12\x1d.chat.GetConversationsRequest\x1a\x1b.chat.ConversationsResponse\x12]\n" +
	"\x15GetConversationDetail\x12\".chat.GetConversationDetailRequest\x1a .chat.ConversationDetailResponse\x12;\n" +
	"\n" +
	"AddMembers\x12\x17.chat.AddMembersRequest\x1a\x14.chat.CommonResponse\x12A\n" +
	"\rRemoveMembers\x12\x1a.chat.RemoveMembersRequest\x1a\x14.chat.CommonResponse\x12I\n" +
	"\x11UpdateUnreadCount\x12\x1e.chat.UpdateUnreadCountRequest\x1a\x14.chat.CommonResponse\x127\n" +
	"\bMarkRead\x12\x15.chat.MarkReadRequest\x1a\x14.chat.CommonResponse\x12S\n" +
	"\x16UpdateConversationInfo\x12#.chat.UpdateConversationInfoRequest\x1a\x14.chat.CommonResponse\x12B\n" +
	"\vCheckMember\x12\x18.chat.CheckMemberRequest\x1a\x19.chat.CheckMemberResponseB\bZ\x06./chatb\x06proto3"

var (
	file_api_proto_beehive_chat_v1_chat_proto_rawDescOnce sync.Once
	file_api_proto_beehive_chat_v1_chat_proto_rawDescData []byte
)

func file_api_proto_beehive_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_api_proto_beehive_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_proto_beehive_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_beehive_chat_v1_chat_proto_rawDesc), len(file_api_proto_beehive_chat_v1_chat_proto_rawDesc)))
	})
	return file_api_proto_beehive_chat_v1_chat_proto_rawDescData
}

var file_api_proto_beehive_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_beehive_chat_v1_chat_proto_goTypes = []any{
	(*CreateConversationRequest)(nil),     // 0: chat.CreateConversationRequest
	(*CreateConversationResponse)(nil),    // 1: chat.CreateConversationResponse
	(*GetConversationsRequest)(nil),       // 2: chat.GetConversationsRequest
	(*ConversationsResponse)(nil),         // 3: chat.ConversationsResponse
	(*ConversationInfo)(nil),              // 4: chat.ConversationInfo
	(*GetConversationDetailRequest)(nil),  // 5: chat.GetConversationDetailRequest
	(*ConversationDetailResponse)(nil),    // 6: chat.ConversationDetailResponse
	(*MemberInfo)(nil),                    // 7: chat.MemberInfo
	(*AddMembersRequest)(nil),             // 8: chat.AddMembersRequest
	(*RemoveMembersRequest)(nil),          // 9: chat.RemoveMembersRequest
	(*UpdateUnreadCountRequest)(nil),      // 10: chat.UpdateUnreadCountRequest
	(*MarkReadRequest)(nil),               // 11: chat.MarkReadRequest
	(*UpdateConversationInfoRequest)(nil), // 12: chat.UpdateConversationInfoRequest
	(*CheckMemberRequest)(nil),            // 13: chat.CheckMemberRequest
	(*CheckMemberResponse)(nil),           // 14: chat.CheckMemberResponse
	(*CommonResponse)(nil),                // 15: chat.CommonResponse
}
var file_api_proto_beehive_chat_v1_chat_proto_depIdxs = []int32{
	4,  // 0: chat.ConversationsResponse.conversations:type_name -> chat.ConversationInfo
	7,  // 1: chat.ConversationDetailResponse.members:type_name -> chat.MemberInfo
	0,  // 2: chat.ChatService.CreateConversation:input_type -> chat.CreateConversationRequest
	2,  // 3: chat.ChatService.GetConversations:input_type -> chat.GetConversationsRequest
	5,  // 4: chat.ChatService.GetConversationDetail:input_type -> chat.GetConversationDetailRequest
	8,  // 5: chat.ChatService.AddMembers:input_type -> chat.AddMembersRequest
	9,  // 6: chat.ChatService.RemoveMembers:input_type -> chat.RemoveMembersRequest
	10, // 7: chat.ChatService.UpdateUnreadCount:input_type -> chat.UpdateUnreadCountRequest
	11, // 8: chat.ChatService.MarkRead:input_type -> chat.MarkReadRequest
	12, // 9: chat.ChatService.UpdateConversationInfo:input_type -> chat.UpdateConversationInfoRequest
	13, // 10: chat.ChatService.CheckMember:input_type -> chat.CheckMemberRequest
	1,  // 11: chat.ChatService.CreateConversation:output_type -> chat.CreateConversationResponse
	3,  // 12: chat.ChatService.GetConversations:output_type -> chat.ConversationsResponse
	6,  // 13: chat.ChatService.GetConversationDetail:output_type -> chat.ConversationDetailResponse
	15, // 14: chat.ChatService.AddMembers:output_type -> chat.CommonResponse
	15, // 15: chat.ChatService.RemoveMembers:output_type -> chat.CommonResponse
	15, // 16: chat.ChatService.UpdateUnreadCount:output_type -> chat.CommonResponse
	15, // 17: chat.ChatService.MarkRead:output_type -> chat.CommonResponse
	15, // 18: chat.ChatService.UpdateConversationInfo:output_type -> chat.CommonResponse
	14, // 19: chat.ChatService.CheckMember:output_type -> chat.CheckMemberResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_beehive_chat_v1_chat_proto_init() }
func file_api_proto_beehive_chat_v1_chat_proto_init() {
	if File_api_proto_beehive_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_beehive_chat_v1_chat_proto_rawDesc), len(file_api_proto_beehive_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_beehive_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_proto_beehive_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_api_proto_beehive_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_api_proto_beehive_chat_v1_chat_proto = out.File
	file_api_proto_beehive_chat_v1_chat_proto_goTypes = nil
	file_api_proto_beehive_chat_v1_chat_proto_depIdxs = nil
}
