// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: conversation.proto

package conversationservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive/services/conversation/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddMemberRequest              = pb.AddMemberRequest
	AddMemberResponse             = pb.AddMemberResponse
	ConversationInfo              = pb.ConversationInfo
	CreateConversationRequest              = pb.CreateConversationRequest
	CreateConversationResponse             = pb.CreateConversationResponse
	FindOrCreateSingleConversationRequest  = pb.FindOrCreateSingleConversationRequest
	FindOrCreateSingleConversationResponse = pb.FindOrCreateSingleConversationResponse
	GetConversationRequest                 = pb.GetConversationRequest
	GetConversationResponse                = pb.GetConversationResponse
	ListMembersRequest                     = pb.ListMembersRequest
	ListMembersResponse                    = pb.ListMembersResponse
	ListUserConversationsRequest           = pb.ListUserConversationsRequest
	ListUserConversationsResponse          = pb.ListUserConversationsResponse
	MemberInfo                             = pb.MemberInfo
	RemoveMemberRequest    = pb.RemoveMemberRequest
	RemoveMemberResponse   = pb.RemoveMemberResponse

	ApplyJoinGroupRequest    = pb.ApplyJoinGroupRequest
	ApplyJoinGroupResponse   = pb.ApplyJoinGroupResponse
	ListJoinRequestsRequest  = pb.ListJoinRequestsRequest
	ListJoinRequestsResponse = pb.ListJoinRequestsResponse
	ApproveJoinRequestRequest  = pb.ApproveJoinRequestRequest
	ApproveJoinRequestResponse = pb.ApproveJoinRequestResponse
	DeclineJoinRequestRequest  = pb.DeclineJoinRequestRequest
	DeclineJoinRequestResponse = pb.DeclineJoinRequestResponse

	ConversationService interface {
		CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error)
		AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error)
		RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
		ListUserConversations(ctx context.Context, in *ListUserConversationsRequest, opts ...grpc.CallOption) (*ListUserConversationsResponse, error)
		GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
		ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
		FindOrCreateSingleConversation(ctx context.Context, in *FindOrCreateSingleConversationRequest, opts ...grpc.CallOption) (*FindOrCreateSingleConversationResponse, error)
		ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupRequest, opts ...grpc.CallOption) (*ApplyJoinGroupResponse, error)
		ListJoinRequests(ctx context.Context, in *ListJoinRequestsRequest, opts ...grpc.CallOption) (*ListJoinRequestsResponse, error)
		ApproveJoinRequest(ctx context.Context, in *ApproveJoinRequestRequest, opts ...grpc.CallOption) (*ApproveJoinRequestResponse, error)
		DeclineJoinRequest(ctx context.Context, in *DeclineJoinRequestRequest, opts ...grpc.CallOption) (*DeclineJoinRequestResponse, error)
	}

	defaultConversationService struct {
		cli zrpc.Client
	}
)

func NewConversationService(cli zrpc.Client) ConversationService {
	return &defaultConversationService{
		cli: cli,
	}
}

func (m *defaultConversationService) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.CreateConversation(ctx, in, opts...)
}

func (m *defaultConversationService) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.AddMember(ctx, in, opts...)
}

func (m *defaultConversationService) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.RemoveMember(ctx, in, opts...)
}

func (m *defaultConversationService) ListUserConversations(ctx context.Context, in *ListUserConversationsRequest, opts ...grpc.CallOption) (*ListUserConversationsResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ListUserConversations(ctx, in, opts...)
}

func (m *defaultConversationService) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.GetConversation(ctx, in, opts...)
}

func (m *defaultConversationService) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ListMembers(ctx, in, opts...)
}

func (m *defaultConversationService) FindOrCreateSingleConversation(ctx context.Context, in *FindOrCreateSingleConversationRequest, opts ...grpc.CallOption) (*FindOrCreateSingleConversationResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.FindOrCreateSingleConversation(ctx, in, opts...)
}

func (m *defaultConversationService) ApplyJoinGroup(ctx context.Context, in *ApplyJoinGroupRequest, opts ...grpc.CallOption) (*ApplyJoinGroupResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ApplyJoinGroup(ctx, in, opts...)
}

func (m *defaultConversationService) ListJoinRequests(ctx context.Context, in *ListJoinRequestsRequest, opts ...grpc.CallOption) (*ListJoinRequestsResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ListJoinRequests(ctx, in, opts...)
}

func (m *defaultConversationService) ApproveJoinRequest(ctx context.Context, in *ApproveJoinRequestRequest, opts ...grpc.CallOption) (*ApproveJoinRequestResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.ApproveJoinRequest(ctx, in, opts...)
}

func (m *defaultConversationService) DeclineJoinRequest(ctx context.Context, in *DeclineJoinRequestRequest, opts ...grpc.CallOption) (*DeclineJoinRequestResponse, error) {
	client := pb.NewConversationServiceClient(m.cli.Conn())
	return client.DeclineJoinRequest(ctx, in, opts...)
}
